apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foglamp.fullname" . }}-deployment
  labels:
    app: foglamp-deployment
    name: foglamp-deployment
  {{- include "foglamp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: foglamp-deployment
      name: foglamp-deployment
    {{- include "foglamp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: foglamp-deployment
        name: foglamp-deployment
      {{- include "foglamp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: FOGLAMP_ROOT
          value: {{ quote .Values.deployment.foglampDeployment.env.foglampRoot }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.deployment.foglampDeployment.image.repository }}:{{ .Values.deployment.foglampDeployment.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.deployment.foglampDeployment.imagePullPolicy }}
        name: foglamp-deployment
        ports:
        - containerPort: 443
          name: api
          protocol: TCP
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
