apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "foglamp.fullname" . }}-foglamp
  labels:
  {{- include "foglamp.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: foglamp-gui
    http:
      paths:
      - backend:
          serviceName: foglamp-deployment
          servicePort: 80
  - host: foglamp-api
    http:
      paths:
      - backend:
          serviceName: foglamp-deployment
          servicePort: 443
